"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { LearningRec } from "@/lib/types";

/**
 * The two on-demand AI panels on a role page.
 *
 * Both start from whatever was generated and cached earlier, so the page is
 * useful before anything is clicked and a model outage degrades to "the
 * previous explanation" rather than to an error.
 */

export function ExplainPanel({
  roleId,
  employeeId,
  initialRationale,
  initialModel,
}: {
  roleId: string;
  employeeId: string;
  initialRationale: string | null;
  initialModel: string | null;
}) {
  const [rationale, setRationale] = useState(initialRationale);
  const [model, setModel] = useState(initialModel);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function run() {
    setPending(true);
    setError(null);
    try {
      const response = await fetch("/api/match/explain", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ roleId, employeeId }),
      });
      const body = await response.json().catch(() => ({}));

      if (!response.ok || !body.rationale) {
        setError(body.error ?? "Could not generate an explanation.");
        return;
      }
      setRationale(body.rationale);
      setModel(body.model ?? null);
    } catch {
      setError("Network problem — try again.");
    } finally {
      setPending(false);
    }
  }

  return (
    <div>
      {rationale ? (
        <p className="whitespace-pre-line text-sm leading-relaxed text-ink">{rationale}</p>
      ) : (
        <p className="text-sm text-muted">
          No explanation generated yet. The score above is already final — this only
          puts it into words.
        </p>
      )}

      {error ? (
        <p
          role="alert"
          className="mt-3 rounded-lg border border-bad/30 bg-bad/10 px-3 py-2 text-sm text-bad"
        >
          {error}
        </p>
      ) : null}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={run}
          disabled={pending}
          className="rounded-lg border border-accent/40 bg-accent-soft px-3.5 py-2 text-sm font-medium text-accent transition hover:bg-accent/20 disabled:opacity-50"
        >
          {pending ? "Writing…" : rationale ? "Regenerate" : "Explain my fit"}
        </button>
        {model ? <span className="text-xs text-muted">generated by {model}</span> : null}
      </div>
    </div>
  );
}

export function RoadmapPanel({
  roleId,
  employeeId,
  initialItems,
  hasGaps,
}: {
  roleId: string;
  employeeId: string;
  initialItems: LearningRec[];
  hasGaps: boolean;
}) {
  const router = useRouter();
  const [items, setItems] = useState(initialItems);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const totalHours = items.reduce((sum, item) => sum + item.effort_hours, 0);

  async function run() {
    setPending(true);
    setError(null);
    setMessage(null);
    try {
      const response = await fetch("/api/roadmap", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ roleId, employeeId }),
      });
      const body = await response.json().catch(() => ({}));

      if (!response.ok) {
        setError(body.error ?? "Could not build a roadmap.");
        return;
      }

      setItems(body.items ?? []);
      if (body.message) setMessage(body.message);
      router.refresh();
    } catch {
      setError("Network problem — try again.");
    } finally {
      setPending(false);
    }
  }

  return (
    <div>
      {items.length > 0 ? (
        <>
          <p className="mb-3 text-xs text-muted">
            {items.length} steps · about {totalHours} hours in total
          </p>
          <ol className="space-y-2">
            {items.map((item, index) => (
              <li
                key={item.id}
                className="rounded-lg border border-line bg-panel-raised/50 px-4 py-3"
              >
                <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                  <span className="text-xs font-semibold text-accent">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                  <span className="text-sm font-medium text-ink">{item.title}</span>
                  <span className="text-xs text-muted">
                    {item.provider} · {item.effort_hours}h · closes {item.skill_name}
                  </span>
                </div>
                <p className="mt-1.5 text-sm leading-relaxed text-muted">
                  {item.rationale}
                </p>
                {item.url ? (
                  <a
                    href={item.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mt-1.5 inline-block text-xs font-medium text-accent hover:underline"
                  >
                    Open resource →
                  </a>
                ) : null}
              </li>
            ))}
          </ol>
        </>
      ) : (
        <p className="text-sm text-muted">
          {hasGaps
            ? "No roadmap yet. Generate one and it will address your gaps in order of importance."
            : "You already meet every requirement for this role — there is nothing to study first."}
        </p>
      )}

      {message ? <p className="mt-3 text-sm text-good">{message}</p> : null}
      {error ? (
        <p
          role="alert"
          className="mt-3 rounded-lg border border-bad/30 bg-bad/10 px-3 py-2 text-sm text-bad"
        >
          {error}
        </p>
      ) : null}

      {hasGaps ? (
        <button
          type="button"
          onClick={run}
          disabled={pending}
          className="mt-4 rounded-lg border border-accent/40 bg-accent-soft px-3.5 py-2 text-sm font-medium text-accent transition hover:bg-accent/20 disabled:opacity-50"
        >
          {pending ? "Planning…" : items.length ? "Rebuild roadmap" : "Build my roadmap"}
        </button>
      ) : null}
    </div>
  );
}
